# Generated by Django 3.0.7 on 2020-06-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200621_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hash',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='txId',
            field=models.CharField(blank=True, default=None, max_length=66, null=True),
        ),
    ]
